version: '3.2'
services:
  db:
    container_name: proto_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - APP_DB_NAME=app_proto
    image: postgres:11.12-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  nest-proto:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    depends_on:
      - 'db'
    profiles:
      - nest-proto  
volumes:
  db_data:
    driver: local      